/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import Models.Customer;
import Service.ChucNang;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Daokh
 */
//class MyModel extends DefaultTableModel{
//    public MyModel() {
//      super(new String[]{"Tên khách hàng", "Số điện thoại","Email", "Người đại diện"}, 0);
//    }
//    @Override
//    public Class<?> getColumnClass(int columnIndex) {
//      Class clazz = String.class;
//      switch (columnIndex) {
//        case 0:
//          clazz = String.class;
//          break;
//        case 2:
//          clazz = Boolean.class;
//          break;
//      }
//      return clazz;
//    }
//    @Override
//    public boolean isCellEditable(int row, int column) {
//      return column == 2;
//    }
//
//    @Override
//    public void setValueAt(Object aValue, int row, int column) {
//      if (aValue instanceof Boolean && column == 2) {
//        System.out.println(aValue);
//        Vector rowData = (Vector)getDataVector().get(row);
//        rowData.set(2, (boolean)aValue);
//        fireTableCellUpdated(row, column);
//      }
//    }
//}

public class ShowKH extends javax.swing.JFrame {

    /**
     * Creates new form ShowKH
     */
    
    public int index = -1;
    List<Customer> list = new ArrayList<>();
    static int Ma_PHG;

    public static int getMa_PHG() {
        return Ma_PHG;
    }

    public static void setMa_PHG(int Ma_PHG) {
        ShowKH.Ma_PHG = Ma_PHG;
    }

    public ShowKH() {
        try {
            initComponents();
            ChucNang.getDBConnection();
            FilltoTable();
        } catch (SQLException ex) {
            Logger.getLogger(ShowKH.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ShowKH.class.getName()).log(Level.SEVERE, null, ex);
        }
//        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }
    DefaultTableModel model;

    public void FilltoTable() throws SQLException {
        list = ChucNang.SelectCus();
        boolean a = false;
        model = (DefaultTableModel) tblCus.getModel();
//model = new DefaultTableModel();
model.setRowCount(0);
        model.setColumnIdentifiers(new String[]{"Tên khách hàng", "Số điện thoại","Email", "Người đại diện"});
        for (Customer x : list) {
            if (x.getMa_KH() == x.getNguoiDD()) {
                a = true;
            } else{
                a= false;
            }
            System.out.println(x.toString());
            model.addRow(new Object[]{x.getHoTen(), x.getSDT(), x.getMail(), a});
        }
//                tblCus.setModel(model);
//        tblCus.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());
//        tblCus.getColumnModel().getColumn(3).setCellEditor(new ButtonEditor());
    }

    public void mouseClick(int index) {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCus = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblCus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Điện thoại", "Email", "Người đại diện"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCus.getTableHeader().setReorderingAllowed(false);
        tblCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCus);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCapnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCapnhat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//       this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
//        this.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void tblCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCusMouseClicked
        // TODO add your handling code here:
        index = tblCus.getSelectedRow();
        boolean a =(list.get(index).getNguoiDD() == list.get(index).getMa_KH()) ? true:false;
        boolean b = (boolean) tblCus.getValueAt(index, 3);
        if(a==b){
//            tblCus;
        }
    }//GEN-LAST:event_tblCusMouseClicked
    Customer c;
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {

            // TODO add your handling code here:
//            boolean ndd = false;
//            index = tblCus.getSelectedRow();
//            String name = (String) model.getValueAt(index, 0);
//            String sdt = (String) model.getValueAt(index, 1);
//            String email = (String) model.getValueAt(index, 2);
            String name = JOptionPane.showInputDialog(this, "Nhập tên");
            if (name.equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập name");
                return;
            }
            String sdt = JOptionPane.showInputDialog(this, "Nhập SDT");
            if (sdt.equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập sdt");
                return;
            } else if(!sdt.matches("\\d{9,10}")){
                 JOptionPane.showMessageDialog(this, "Bạn vui lòng nhập đúng định dạng sdt");
               return ;
            }
            String reEmail = "^([\\w\\.\\-]+)@([\\w\\-]+)((\\.(\\w){2,3})+)$";
            String email = JOptionPane.showInputDialog(this, "Nhập Email");
            if (email.equals("")) {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập email");
                return;
            } else if (reEmail.matches(reEmail) == false) {
                JOptionPane.showMessageDialog(this, "Email khong dung dinh dang", "Loi nhap email", JOptionPane.WARNING_MESSAGE);
                // txtEmail.setBackground(Color.yellow);
                // txtEmail.requestFocus();
                return;
            }
//            if (list.size() == 0) {
//                ndd = true;
//            }
//            System.out.println("," + name + "," + sdt+","+email+","+Ma_PHG);
            ChucNang.InsertKH(name, sdt, email);
            JOptionPane.showMessageDialog(this, "thanhcong");

        } catch (SQLException ex) {
            Logger.getLogger(ShowKH.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        try {
            index = tblCus.getSelectedRow();
            ChucNang.deleteKH(list.get(index).getMa_KH());
//            list.remove(index);
            FilltoTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        } catch (SQLException ex) {
            Logger.getLogger(ShowKH.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed
    private int makh;
    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        try {
            boolean ndd = false;
            //            index = tblCus.getSelectedRow();
            for (int i = 0; i < list.size(); i++) {
                String name = (String) model.getValueAt(i, 0);
                String sdt = (String) model.getValueAt(i, 1);
                String email = (String) model.getValueAt(i, 2);
                boolean checkndd = (boolean) model.getValueAt(i, 3);
                System.out.println(name + "," + sdt + "," + email + "," + checkndd);
                if (checkndd) {
                    ChucNang.UpdateNguoiDD(list.get(i).getMa_KH(), list.get(i).getMa_PHG());
                }
                ChucNang.UpdateKH(name, sdt, email, list.get(i).getMa_KH());

//                JOptionPane.showMessageDialog(this, "thanhcong");
            }
            FilltoTable();
        } catch (SQLException ex) {
            Logger.getLogger(ShowKH.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCapnhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowKH.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowKH.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowKH.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowKH.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowKH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCus;
    // End of variables declaration//GEN-END:variables
}
